version: 2
general:
  branches:
    only:
      - master
      - develop
jobs:
  build:
    working_directory: ~/hmpps-prototype
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Lint
          command: yarn ng lint --type-check
      - run:
          name: Unit test
          command: yarn ng test --single-run --no-progress --browsers ChromeHeadless
      - run:
          name: Smoke test
          command: yarn ng e2e
      - run:
          name: Production build
          command: yarn ng build --prod --aot --no-progress
