version: 2
jobs:
  build-job:
    working_directory: ~/hmpps-prototype
    docker:
      - image: circleci/node:8.11.1-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: Lint
          command: yarn ng lint --type-check
      - run:
          name: Unit test
          command: yarn ng test --single-run --no-progress --browsers ChromeHeadless
      - run:
          name: Install latest Chrome
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome
      - run:
          name: Smoke test
          command: yarn ng e2e --browsers ChromeHeadless
      - run:
          name: Production build
          command: yarn ng build --prod --build-optimizer --aot --no-progress
      - persist_to_workspace:
          root: ~/hmpps-prototype
          paths:
            - dist
  deploy-job:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run:
          name: Install awscli
          command: |
            sudo apt install python-pip python-dev
            sudo pip install awscli
      - attach_workspace:
          at: ~/hmpps-prototype
      - run:
          name: Deploy to AWS
          command: aws s3 sync ~/hmpps-prototype/dist/ s3://moj-studio.dnt.prototype --acl public-read --sse AES256 --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
