version: 2
general:
  branches:
    only:
      - master
      - develop
jobs:
  build:
    working_directory: ~/hmpps-prototype
    docker:
      - image: circleci/node:6-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-lint
          command: yarn ng -- lint --type-check
      - run:
          name: angular-test
          command: yarn ng -- test --single-run --no-progress
      - run:
          name: angular-build
          command: yarn ng -- build --aot --no-progress
      - run:
          name: angular-production-build
          command: yarn ng -- build --prod --aot --no-progress
