export function prisonsAndYoungOffenderInstitutions(): Array<string> {
  return [
    'Altcourse',
    'Ashfield',
    'Askham Grange',
    'Aylesbury',
    'Bedford',
    'Belmarsh',
    'Berwyn',
    'Birmingham',
    'Blantyre House',
    'Brinsford',
    'Bristol',
    'Brixton',
    'Bronzefield',
    'Buckley Hall',
    'Bullingdon',
    'Bure',
    'Cardiff',
    'Channings Wood',
    'Chelmsford',
    'Coldingley',
    'Cookham Wood',
    'Dartmoor',
    'Deerbolt',
    'Doncaster',
    'Dovegate',
    'Downview',
    'Drake Hall',
    'Durham',
    'East Sutton Park',
    'Eastwood Park',
    'Erlestoke',
    'Exeter',
    'Featherstone',
    'Feltham',
    'Ford',
    'Forest Bank',
    'Foston Hall',
    'Frankland',
    'Full Sutton',
    'Garth',
    'Gartree',
    'Grendon & Springhill',
    'Guys Marsh',
    'Hatfield',
    'Haverigg',
    'Hewell',
    'High Down',
    'Highpoint North',
    'Highpoint South',
    'Hindley',
    'Hollesley Bay',
    'Holme House',
    'Hull',
    'Humber',
    'Huntercombe',
    'Isis',
    'Isle of Wight (Albany)',
    'Isle of Wight (Parkhurst)',
    'Kennet',
    'Kirkham',
    'Kirklevington Grange',
    'Lancaster Farms',
    'Leeds',
    'Leicester',
    'Lewes',
    'Leyhill',
    'Lincoln',
    'Lindholme',
    'Littlehey',
    'Liverpool',
    'Long Lartin',
    'Low Newton',
    'Lowdham Grange',
    'Maidstone',
    'Manchester',
    'Moorland',
    'New Hall',
    'Northumberland',
    'North Sea Camp',
    'Norwich',
    'Nottingham',
    'Oakwood',
    'Onley',
    'Parc',
    'Pentonville',
    'Peterborough',
    'Portland',
    'Prescoed',
    'Preston',
    'Ranby',
    'Risley',
    'Rochester',
    'Rye Hill',
    'Send',
    'Sheppey Cluster (Elmley)',
    'Sheppey Cluster (Standford Hill)',
    'Sheppey Cluster (Swaleside)',
    'Stafford',
    'Stocken',
    'Stoke Heath',
    'Styal',
    'Sudbury',
    'Swansea',
    'Swinfen Hall',
    'Thameside',
    'The Mount',
    'Thorn Cross',
    'Usk',
    'Wakefield',
    'Wandsworth',
    'Warren Hill',
    'Wayland',
    'Wealstun',
    'Werrington',
    'Wetherby',
    'Whatton',
    'Whitemoor',
    'Winchester',
    'Woodhill',
    'Wormwood Scrubs',
    'Wymott'
  ];
}
